# Generated by Django 3.0.8 on 2020-09-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phoneno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'newuser',
            },
        ),
        migrations.CreateModel(
            name='Storefound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectitem', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='pics/')),
                ('description', models.CharField(max_length=100)),
                ('foundername', models.CharField(blank=True, max_length=10)),
                ('markasnotclaim', models.BooleanField(blank=True, default=False)),
                ('returnedstatus', models.IntegerField(blank=True, default=0)),
                ('handovername', models.CharField(blank=True, max_length=20)),
                ('branchname', models.CharField(blank=True, max_length=20)),
                ('useridforeignfound', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfoundweb.Newuser')),
            ],
            options={
                'db_table': 'storefound',
            },
        ),
        migrations.CreateModel(
            name='Storelost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectitem', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('ownername', models.CharField(blank=True, max_length=10)),
                ('reward', models.IntegerField(blank=True, default=0)),
                ('recievedstatus', models.IntegerField(blank=True, default=0)),
                ('lostbranchname', models.CharField(blank=True, max_length=20)),
                ('useridforeign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfoundweb.Newuser')),
            ],
            options={
                'db_table': 'storelost',
            },
        ),
        migrations.CreateModel(
            name='Storereturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('ownername', models.CharField(max_length=10)),
                ('foundername', models.CharField(max_length=10)),
                ('givenstatus', models.IntegerField(blank=True, default=0)),
                ('founderid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfoundweb.Newuser')),
                ('lostitemid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfoundweb.Storelost')),
            ],
            options={
                'db_table': 'storereturn',
            },
        ),
        migrations.CreateModel(
            name='Storematching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('founditemid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfoundweb.Storefound')),
                ('lostitemid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfoundweb.Storelost')),
            ],
            options={
                'db_table': 'storematching',
            },
        ),
        migrations.CreateModel(
            name='Storeclaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('foundername', models.CharField(max_length=10)),
                ('claimername', models.CharField(max_length=10)),
                ('givenstatus', models.IntegerField(blank=True, default=0)),
                ('claimerid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfoundweb.Newuser')),
                ('founditemid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lostandfoundweb.Storefound')),
            ],
            options={
                'db_table': 'storeclaim',
            },
        ),
    ]
